### ISSUE TITLE
Environtment setup

### ISSUE THREAD

**Issue by suckkay** [zzt93/syncer#5]
am using ubuntu 18~

java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.10.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

mvn -version
Apache Maven 3.5.4

when i try to run 
`java -server -XX:+UseG1GC -jar ./syncer-core/target/syncer-core-1.0-SNAPSHOT.jar --port=40000  --host_address=192.168.55.101 --config=syncer-config.yml --producerConfig=sample-producer.yml --comsumerConfig=my-consumer.yml `

path is correct 

i got this error 
``
```
019-02-15 16:36:21,820 ERROR [] [syncer@ACTIVE_PROFILE_IS_UNDEFINED@HOST_ADDRESS_IS_UNDEFINED] --- [syncer-shutdown-starter] com.github.zzt93.syncer.ShutDownCenter   : [Shutting down] Init
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=syncer for JavaBean=com.github.zzt93.syncer.config.syncer.SyncerConfig@60c6f5b
 in 'string', line 1, column 1:
    syncer:
    ^
Unable to find property 'syncer' on class: com.github.zzt93.syncer.config.syncer.SyncerConfig
 in 'string', line 2, column 3:
      ack:
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:501)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor.initConfig(YamlEnvironmentPostProcessor.java:129)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor.processEnvironment(YamlEnvironmentPostProcessor.java:52)
	at com.github.zzt93.syncer.SyncerApplication.main(SyncerApplication.java:41)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'syncer' on class: com.github.zzt93.syncer.config.syncer.SyncerConfig
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:189)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:178)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor$1.getProperty(YamlEnvironmentPostProcessor.java:144)
	at org.yaml.snakeyaml.TypeDescription.discoverProperty(TypeDescription.java:240)
	at org.yaml.snakeyaml.TypeDescription.getProperty(TypeDescription.java:251)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:210)
	... 11 common frames omitted
2019-02-15 16:45:47,122 ERROR [] [syncer@ACTIVE_PROFILE_IS_UNDEFINED@HOST_ADDRESS_IS_UNDEFINED] --- [syncer-shutdown-starter] com.github.zzt93.syncer.ShutDownCenter   : [Shutting down] Init
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=syncer for JavaBean=com.github.zzt93.syncer.config.syncer.SyncerConfig@60c6f5b
 in 'string', line 1, column 1:
    syncer:
    ^
Unable to find property 'syncer' on class: com.github.zzt93.syncer.config.syncer.SyncerConfig
 in 'string', line 2, column 3:
      ack:
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:501)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor.initConfig(YamlEnvironmentPostProcessor.java:129)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor.processEnvironment(YamlEnvironmentPostProcessor.java:52)
	at com.github.zzt93.syncer.SyncerApplication.main(SyncerApplication.java:41)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'syncer' on class: com.github.zzt93.syncer.config.syncer.SyncerConfig
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:189)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:178)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor$1.getProperty(YamlEnvironmentPostProcessor.java:144)
	at org.yaml.snakeyaml.TypeDescription.discoverProperty(TypeDescription.java:240)
	at org.yaml.snakeyaml.TypeDescription.getProperty(TypeDescription.java:251)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:210)
	... 11 common frames omitted
2019-02-15 16:47:42,894 ERROR [] [syncer@ACTIVE_PROFILE_IS_UNDEFINED@HOST_ADDRESS_IS_UNDEFINED] --- [syncer-shutdown-starter] com.github.zzt93.syncer.ShutDownCenter   : [Shutting down] Init
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=syncer for JavaBean=com.github.zzt93.syncer.config.syncer.SyncerConfig@60c6f5b
 in 'string', line 1, column 1:
    syncer:
    ^
Unable to find property 'syncer' on class: com.github.zzt93.syncer.config.syncer.SyncerConfig
 in 'string', line 2, column 3:
      ack:
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:501)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor.initConfig(YamlEnvironmentPostProcessor.java:129)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor.processEnvironment(YamlEnvironmentPostProcessor.java:52)
	at com.github.zzt93.syncer.SyncerApplication.main(SyncerApplication.java:41)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'syncer' on class: com.github.zzt93.syncer.config.syncer.SyncerConfig
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:189)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:178)
	at com.github.zzt93.syncer.config.YamlEnvironmentPostProcessor$1.getProperty(YamlEnvironmentPostProcessor.java:144)
	at org.yaml.snakeyaml.TypeDescription.discoverProperty(TypeDescription.java:240)
	at org.yaml.snakeyaml.TypeDescription.getProperty(TypeDescription.java:251)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:210)
	... 11 common frames omitted
`````

**Comment by zzt93** [comment]
Sorry that my readme give an out-dated example of `syncer.yml`. I have fix the problem. The following is a right example:
```yml
port: 12345
ack:
  flushPeriod: 100
input:
  input-meta:
    last-run-metadata-dir: /data/syncer/input/last_position/

filter:
  worker: 3
  
output:
  worker: 2
  batch:
    worker: 2
  output-meta:
    failure-log-dir: /data/syncer/output/failure/
```

Notify me if you need more help.

**Comment by suckkay** [comment]
${HOST_ADDRESS}
${ACTIVE_PROFILE}

is this two are bash path?

**Comment by zzt93** [comment]
It is environment variable, you can define by export.

**Comment by suckkay** [comment]
```
sakairock@WORK:~/Documents/work/syncer$ echo ${HOST_ADDRESS}
192.168.55.101
sakairock@WORK:~/Documents/work/syncer$ echo ${ACTIVE_PROFILE}
dev
```
`sudo java -server -XX:+UseParallelOldGC -jar ./syncer-core/target/syncer-core-1.0-SNAPSHOT.jar [--address=192.168.55.101] --producerConfig=producer.yml `


my-consumer.yml 

```
version: 1.2

consumerId: searcher

input:
  masters:
  - connection:
      address: ${HOST_ADDRESS}
      port: 3306
    scheduler: mod
    repos:
    - name: "database_name"
      entities:
      - name: field1
        fields: [id,title,author]
      - name: field2
        fields: [id,title,author]
    





output:
  elasticsearch:
    connection:
      clusterName: test-${ACTIVE_PROFILE}
      clusterNodes: ["${HOST_ADDRESS}:9200"]
    requestMapping: # mapping from input data to es request
      enableExtraQuery: true
      retryOnUpdateConflict: 3
      index: "es_index"
      type: "data" # default: table
      documentId: "id" # default: id
    batch:
      size: 100
      delay: 1000
      maxRetry: 5
    refreshInMillis: 1000


```
syncer.yml
```
ack:
  flushPeriod: 100
input:
  input-meta:
    last-run-metadata-dir: /data/syncer/input/last_position/

filter:
  worker: 3
  
output:
  worker: 2
  batch:
    worker: 2
  output-meta:
    failure-log-dir: /data/syncer/output/failure/

```
producer.yml
```
syncer.producer.input:
  masters:
    - connection:
        address: ${HOST_ADDRESS}
        port: 3306
        user: root
        password: password

```

**Comment by zzt93** [comment]
:(, Oh so sorry that my producer config is also outdated.

the following is right example: 
```
input:
  masters:
    - connection:
        address: ${HOST_ADDRESS}
        port: 3306
        user: root
        password: password
```

By the way, in consumer input config, notice:
```
    repos:
    - name: "database_name"
      entities:
      - name: field1   <---- here is "table_name"
        fields: [id,title,author]
      - name: field2   <---- here is "table_name"
        fields: [id,title,author]
```
in output config:
```
    requestMapping: # mapping from input data to es request
      enableExtraQuery: true
      retryOnUpdateConflict: 3
      index: "es_index"    <--- may be " 'es_index' "
      type: "data" # default: table  <-- " 'data' "
      documentId: "id" # default: id
```
Notice in `Spring EL', " 'data' " is a `String`, but "data" is a variable.

**Comment by suckkay** [comment]
yes. i understand the input and output of consumer configuration 

but i found new error 

`com.github.zzt93.syncer.config.common.SchemaUnavailableException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up`

is this because am using mariadb ?

**Comment by zzt93** [comment]
No, it should be no difference. Are you sure the password in `producer.yml` is right?

**Comment by suckkay** [comment]
```
yes. the password correct
i had to give access to  <ip-address>  for accessing the MariaDB. its now can connect to the DB.  
but 

maybe some config were missing again :) 

i got this error 
```

sakairock@WORK:~/Documents/work/syncer$ java -server -XX:+UseParallelOldGC -jar ./syncer-core/target/syncer-core-1.0-SNAPSHOT.jar --config=syncer.yml --producerConfig=producer.yml --consumerConfig=my-consumer.yml
2019-02-18 19:16:07,214  WARN [] [syncer@dev@192.168.55.101] --- [main] c.github.zzt93.syncer.consumer.ack.Ack   : Meta file in /home/sakairock/Documents/work/syncer/data/syncer/input/last_position/searcher/192.168.55.101:3306 crashed, take as fresh run
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Feb 18, 2019 7:16:10 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
WARNING: Binary log position adjusted from 0 to 4
Feb 18, 2019 7:16:10 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 192.168.55.101:3306 at /4 (sid:2100550919, cid:44)
2019-02-18 19:16:10,280  WARN [bin.000001/445/81/u] [syncer@dev@192.168.55.101] --- [syncer-filter-output-1-4] c.g.z.s.c.o.c.e.ElasticsearchChannel     : Include primary key in `_source` is usually not necessary, remove it
2019-02-18 19:16:10,286 ERROR [bin.000001/445/81/u] [syncer@dev@192.168.55.101] --- [syncer-filter-output-1-4] c.g.z.syncer.consumer.filter.FilterJob   : Output SyncData{inner=Meta{eventId='bin.000001/445/81/u', dataId='bin.000001/445/81/u/0', ordinal=0, context=org.springframework.expression.spel.support.StandardEvaluationContext@307e67b7, hasExtra=false, connectionIdentifier='192.168.55.101:3306'}, syncByQuery=null, result=SyncResult{fields={author=me, title=[B@1c80ce65}, extra={}, eventType=UPDATE, repo='databasenem', entity='tablename', id=25563, primaryKeyName='id'}} failed


```

**Comment by zzt93** [comment]
Can you show the `consumer` config about 'penduduk'? The error is always means you config a `Spring EL` expression with simple 'penduduk' and it try to parse it like a field of object. May be you want quote it with single quote in config file?

**Comment by suckkay** [comment]
this is my complete configuration
```
version: 1.2

consumerId: searcher

input:
  masters:
  - connection:
      address: ${HOST_ADDRESS}
      port: 3306
    scheduler: mod
    repos:
    - name: "penduduk_news"
      entities:
      - name: detik_news
        fields: [id,title,author]
      - name: merdeka_news
        fields: [id,title,author]
    





output:
  elasticsearch:
    connection:
      clusterName: test-${ACTIVE_PROFILE}
      clusterNodes: ["${HOST_ADDRESS}:9200"]
    requestMapping: # mapping from input data to es request
      enableExtraQuery: true
      retryOnUpdateConflict: 3
      index: "penduduk"
      type: "data" # default: table
    batch:
      size: 100
      delay: 1000
      maxRetry: 5
    refreshInMillis: 1000


```

**Comment by zzt93** [comment]
```
output:
  elasticsearch:
    connection:
      clusterName: test-${ACTIVE_PROFILE}
      clusterNodes: ["${HOST_ADDRESS}:9200"]    <-- might be 9300
    requestMapping: # mapping from input data to es request
      enableExtraQuery: true
      retryOnUpdateConflict: 3
      index: "penduduk"  <--  is your index 'penduduk'? if so, it should be " 'penduduk' "
      type: "data" # default: table
    batch:
      size: 100
      delay: 1000
      maxRetry: 5
    refreshInMillis: 1000
```

**Comment by suckkay** [comment]
this is the error before that

```
Feb 18, 2019 7:53:29 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 192.168.55.101:3306 at bin.000001/445 (sid:297318640, cid:52)
2019-02-18 19:53:29,338  WARN [bin.000001/445/81/u] [syncer@dev@192.168.55.101] --- [syncer-filter-output-1-4] c.g.z.s.c.o.c.e.ElasticsearchChannel     : Include primary key in `_source` is usually not necessary, remove it
2019-02-18 19:53:29,345 ERROR [bin.000001/445/81/u] [syncer@dev@192.168.55.101] --- [syncer-filter-output-1-4] c.g.z.syncer.consumer.filter.FilterJob   : Output SyncData{inner=Meta{eventId='bin.000001/445/81/u', dataId='bin.000001/445/81/u/0', ordinal=0, context=org.springframework.expression.spel.support.StandardEvaluationContext@508dad32, hasExtra=false, connectionIdentifier='192.168.55.101:3306'}, syncByQuery=null, result=SyncResult{fields={author=arif rahman, title=[B@f09627b}, extra={}, eventType=UPDATE, repo='penduduk_news', entity='detik_news', id=25563, primaryKeyName='id'}} failed

```

**Comment by zzt93** [comment]
What is your target index name?
if it is fixed
 - use `" 'penduduk' "`

if it is a variable
- use `Spring EL` expression, 
  - like field of `SyncResult`: repo, entity, id; 
  - temp variable defined in `filter`: #temp 
```
output:
  elasticsearch:
    connection:
      clusterName: test-${ACTIVE_PROFILE}
      clusterNodes: ["${HOST_ADDRESS}:9200"]    <-- might be 9300
    requestMapping: # mapping from input data to es request
      enableExtraQuery: true
      retryOnUpdateConflict: 3
      index: "penduduk"  <--  is your index 'penduduk'? if so, it should be " 'penduduk' "
      type: "data" # default: table
    batch:
      size: 100
      delay: 1000
      maxRetry: 5
    refreshInMillis: 1000
```

**Comment by suckkay** [comment]
yes am using 

> 'penduduk

**Comment by zzt93** [comment]
Sorry to let you wait for so long, I don't why no notification for your msg. 

As you provided log, I can see no error. So I assume it works. You can exec the following bash command to verify the index:
```
 curl -s -X GET "localhost:9200/_cat/indices?v"
```
And following to get count (notice to replace env variable with your target):
```
curl -s -X GET "localhost:9200/${index}/${type}/_count" -H 'Content-Type: application/json'
```

If you are not sure about the config, you may see the [test config](https://github.com/zzt93/syncer/tree/master/test/config) for check, which is tested with docker/docker-compose.

If still not work, leave me a message.
